### ISSUE TITLE
NBA dataset removed from Kaggle

### ISSUE THREAD

**Issue by ryanwcyin** [wyattowalsh/nba-db#5]
The NBA dataset removed from Kaggle

**To Reproduce**
`kaggle datasets download --unzip -o -q -d wyattowalsh/basketball`

**Expected behavior**
The dataset is downloaded, but received `403 - Forbidden`

**Comment by wyattowalsh** [comment]
I accidentally ran the database compiler script in a Kaggle Notebook so my account was temporarily banned.

This should be fixed now! 👍
